In [0]:
import pandas as pd
import numpy as np
from datetime import datetime

# Sample data with missing values
data = {
    "OrderID": ["ORD001", "ORD002", "ORD003", "ORD004", "ORD005", "ORD006"],
    "CustomerID": ["CUST001", "CUST002", "CUST003", "CUST002", "CUST004", "CUST001"],
    "ProductID": ["P001", "P002", "P003", "P004", "P005", "P006"],
    "OrderDate": ["2024-12-01", "2024-12-01", "2024-12-02", "2024-12-03", "2024-12-03", "2024-12-04"],
    "Quantity": [2, 1, 3, 2, 5, np.nan],
    "UnitPrice": [250.0, 120.0, 75.5, 500.0, np.nan, 90.0],
    "Category": ["Electronics", "Clothing", "Grocery", "Electronics", "Clothing", "Grocery"],
    "Store": ["Store_A", "Store_B", "Store_A", "Store_C", "Store_B", "Store_A"]
}

df = pd.DataFrame(data)
df

#convert orderdate to datetime format 
df["OrderDate"]= pd.to_datetime(df["OrderDate"])
# Fill missing Quantity with median and UnitPrice with mean
df["Quantity"].fillna(df["Quantity"].median(),inplace=True)
df["UnitPrice"].fillna(df["UnitPrice"].mean(),inplace =True)
# Remove duplicates (if any)
df.drop_duplicates(inplace=True)

#Derive New Columns

#Total Price
df["TotalPrice"]= df["Quantity"]*df["UnitPrice"]

df["discount"]= np.where(df["TotalPrice"]>400,0.10,0.05)

df["FinalPrice"]=df["TotalPrice"]*(1-df["discount"])

df

  OrderID CustomerID ProductID  ... TotalPrice  discount  FinalPrice
0  ORD001    CUST001      P001  ...      500.0      0.10     450.000
1  ORD002    CUST002      P002  ...      120.0      0.05     114.000
2  ORD003    CUST003      P003  ...      226.5      0.05     215.175
3  ORD004    CUST002      P004  ...     1000.0      0.10     900.000
4  ORD005    CUST004      P005  ...     1035.5      0.10     931.950
5  ORD006    CUST001      P006  ...      180.0      0.05     171.000

[6 rows x 11 columns]